services:
  - type: web
    name: ragops-service
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn RAGOPSproject.RAGOPS.app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      GROQ_API_KEY: 
        sync: false
      OPENAI_API_KEY:
        sync: false
